---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
    tier: backend
    version: v1
  annotations:
    image.openshift.io/triggers: |-
      [{"from":{"kind":"ImageStreamTag","name":"demo-app:latest","namespace":"it22-kafka-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"demo-app\")].image","pause":"false"}]
  namespace: it22-kafka-dev
spec:
  selector:
    matchLabels:
      app: demo-app
      tier: backend
      version: v1
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker-serial=worker2
  replicas: 1
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        tier: backend
        version: v1
    spec:
      containers:
        - name: demo-app
          image: 'image-registry.openshift-image-registry.svc:5000/it22-kafka-dev/demo-app:latest'
          ports:
            - containerPort: 4004
          imagePullPolicy: Always   
          env:
            - name: MYSQL_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-app
                  key: mysql.database.username

            - name: MYSQL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app
                  key: mysql.database.password